services:
    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./mnt/postgres:/var/lib/postgresql/data/pgdata

    webserver:
        build:
            context: ./docker/airflow
        image: marclamberti/docker-airflow-security:2.9.0
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - AIRFLOW__WEBSERVER__SECRET_KEY=c45653c1c20f3c536f84280c8bdbe9636f231507f1d978d30c86f50801b6
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
            - ./mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
            context: ./docker/airflow
        image: marclamberti/docker-airflow-security:1.10.9
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            context: ./docker/airflow
        image: marclamberti/docker-airflow-security:1.10.9
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
            - ./mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
        # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        build:
            context: ./docker/airflow
        image: marclamberti/docker-airflow-security:1.10.9
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
            - ./mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker